// Dataset base de provincias argentinas y sus ciudades principales/cabeceras
// más conocidas. No es exhaustivo (no incluye TODAS las localidades del país),
// pero cubre las 24 provincias con varias ciudades representativas de cada una.
// Se puede seguir ampliando desde la pantalla de administración de Localidades.

export const PROVINCIAS_ARGENTINA: Record<string, string[]> = {
  "Ciudad Autónoma de Buenos Aires": ["Ciudad Autónoma de Buenos Aires"],
  "Buenos Aires": [
    "La Plata",
    "Mar del Plata",
    "Bahía Blanca",
    "Tandil",
    "Junín",
    "Pergamino",
    "San Nicolás de los Arroyos",
    "Necochea",
    "Olavarría",
    "Azul",
    "Chivilcoy",
    "Luján",
    "Zárate",
    "Campana",
    "San Pedro",
    "Trenque Lauquen",
    "Pehuajó",
    "Chascomús",
    "Dolores",
    "Balcarce",
    "Quilmes",
    "Avellaneda",
    "Lomas de Zamora",
    "San Isidro",
    "Tigre",
    "Morón",
    "San Justo",
    "Vicente López",
    "Merlo",
    "Moreno",
    "Escobar",
    "Pilar",
  ],
  Catamarca: [
    "San Fernando del Valle de Catamarca",
    "Andalgalá",
    "Belén",
    "Recreo",
    "Tinogasta",
    "Santa María",
  ],
  Chaco: [
    "Resistencia",
    "Presidencia Roque Sáenz Peña",
    "Villa Ángela",
    "Charata",
    "General José de San Martín",
    "Machagai",
  ],
  Chubut: ["Rawson", "Comodoro Rivadavia", "Trelew", "Puerto Madryn", "Esquel", "Sarmiento"],
  Córdoba: [
    "Córdoba",
    "Río Cuarto",
    "Villa María",
    "San Francisco",
    "Alta Gracia",
    "Bell Ville",
    "Villa Carlos Paz",
    "Jesús María",
    "La Falda",
    "Cosquín",
    "Río Tercero",
    "Marcos Juárez",
  ],
  Corrientes: ["Corrientes", "Goya", "Mercedes", "Paso de los Libres", "Curuzú Cuatiá", "Santo Tomé"],
  "Entre Ríos": [
    "Paraná",
    "Concordia",
    "Gualeguaychú",
    "Concepción del Uruguay",
    "Gualeguay",
    "Villaguay",
  ],
  Formosa: ["Formosa", "Clorinda", "Pirané", "El Colorado"],
  Jujuy: [
    "San Salvador de Jujuy",
    "Palpalá",
    "Libertador General San Martín",
    "San Pedro de Jujuy",
    "Perico",
  ],
  "La Pampa": ["Santa Rosa", "General Pico", "Toay", "Realicó"],
  "La Rioja": ["La Rioja", "Chilecito", "Aimogasta", "Chamical"],
  Mendoza: [
    "Mendoza",
    "San Rafael",
    "Godoy Cruz",
    "Guaymallén",
    "Las Heras",
    "Maipú",
    "Luján de Cuyo",
    "General Alvear",
    "Tunuyán",
  ],
  Misiones: ["Posadas", "Oberá", "Eldorado", "Puerto Iguazú", "Apóstoles"],
  Neuquén: [
    "Neuquén",
    "Cutral Có",
    "Plottier",
    "Zapala",
    "San Martín de los Andes",
    "Villa La Angostura",
  ],
  "Río Negro": [
    "Viedma",
    "San Carlos de Bariloche",
    "General Roca",
    "Cipolletti",
    "Villa Regina",
    "El Bolsón",
  ],
  Salta: ["Salta", "San Ramón de la Nueva Orán", "Tartagal", "Metán", "Cafayate"],
  "San Juan": ["San Juan", "Rawson", "Chimbas", "Rivadavia", "Pocito", "Caucete"],
  "San Luis": ["San Luis", "Villa Mercedes", "Merlo", "Concarán"],
  "Santa Cruz": ["Río Gallegos", "Caleta Olivia", "El Calafate", "Puerto Deseado", "Pico Truncado"],
  "Santa Fe": [
    "Santa Fe",
    "Rosario",
    "Rafaela",
    "Venado Tuerto",
    "Reconquista",
    "Villa Gobernador Gálvez",
    "Casilda",
    "San Lorenzo",
    "Esperanza",
  ],
  "Santiago del Estero": [
    "Santiago del Estero",
    "La Banda",
    "Termas de Río Hondo",
    "Añatuya",
    "Fernández",
  ],
  "Tierra del Fuego": ["Ushuaia", "Río Grande", "Tolhuin"],
  Tucumán: [
    "San Miguel de Tucumán",
    "Yerba Buena",
    "Concepción",
    "Tafí Viejo",
    "Banda del Río Salí",
    "Aguilares",
  ],
};
